/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:39:53
 * Time to generate: 01:26.015 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.snapshot.SnapshotHandlerImpl:bf5e6a3876a47c26ce2aea5dd53e3ae3
 * agitar.src.md5=com.huawei.ism.openapi.common.DefaultCommHandler:b6802204ee7c3e439b341a5d028a1348
 *
 */

package com.huawei.ism.openapi.snapshot;

import com.agitar.lib.junit.AgitarTestCase;
import com.agitar.lib.mockingbird.Mockingbird;
import com.huawei.ism.openapi.common.commu.rest.RestManager;
import com.huawei.ism.openapi.common.commu.rest.RestRequestHandler;
import com.huawei.ism.openapi.common.exception.ApiException;
import com.huawei.ism.openapi.common.exception.ApiMessage;
import com.huawei.ism.openapi.common.keydeifines.ConstantsDefine;
import com.huawei.ism.openapi.common.keydeifines.EnumDefine;
import com.huawei.ism.openapi.common.logmanager.LogUtil;
import com.huawei.ism.openapi.common.model.MO;
import com.huawei.ism.openapi.common.model.MOType;
import com.huawei.ism.openapi.common.utils.OpenApiUtils;
import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import org.json.JSONException;
import org.json.JSONObject;

public class SnapshotHandlerImplAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return SnapshotHandlerImpl.class;
    }
    
    public void testConstructor() throws Throwable {
        RestRequestHandler restRequestHandler = new RestRequestHandler("testSnapshotHandlerImplIp", 100);
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(restRequestHandler, "testSnapshotHandlerImplDeviceID");
        assertNull("snapshotHandlerImpl.snapshotIterator", getPrivateField(snapshotHandlerImpl, "snapshotIterator"));
        assertEquals("snapshotHandlerImpl.deviceID", "testSnapshotHandlerImplDeviceID", getPrivateField(snapshotHandlerImpl, "deviceID"));
        assertSame("snapshotHandlerImpl.restRequestHandler", restRequestHandler, getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
    }
    
    public void testCreateWithAggressiveMocks() throws Throwable {
        storeStaticField(MOType.class, "HOST");
        storeStaticField(EnumDefine.LOG_TYPE_E.class, "LOG_INFO");
        SnapshotHandlerImpl snapshotHandlerImpl = (SnapshotHandlerImpl) Mockingbird.getProxyObject(SnapshotHandlerImpl.class, true);
        SnapshotMO snapshotMO = (SnapshotMO) Mockingbird.getProxyObject(SnapshotMO.class);
        MO mO = (MO) Mockingbird.getProxyObject(MO.class);
        OpenApiUtils openApiUtils = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        MOType mOType = (MOType) Mockingbird.getProxyObject(MOType.class);
        Map map = (Map) Mockingbird.getProxyObject(Map.class);
        LogUtil logUtil = (LogUtil) Mockingbird.getProxyObject(LogUtil.class);
        OpenApiUtils openApiUtils2 = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        setPrivateField(snapshotHandlerImpl, "deviceID", "");
        setPrivateField(snapshotHandlerImpl, "restRequestHandler", null);
        setPrivateField(snapshotMO, "mo", mO);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils);
        setPrivateField(MOType.class, "HOST", mOType);
        setPrivateField(mOType, "value", new Integer(0));
        setPrivateField(mO, "properties", map);
        setPrivateField(EnumDefine.LOG_TYPE_E.class, "LOG_INFO", null);
        Mockingbird.setReturnValue(false, openApiUtils, "composeRelativeUri", "(java.lang.String[])java.lang.String", "", 1);
        JSONObject jSONObject = (JSONObject) Mockingbird.getProxyObject(JSONObject.class);
        Mockingbird.replaceObjectForRecording(JSONObject.class, "<init>()", jSONObject);
        Mockingbird.setReturnValue(jSONObject.put("TYPE", 0), null);
        Mockingbird.setReturnValue(LogUtil.getLogUtilInstance(), logUtil);
        Mockingbird.setReturnValue(false, map, "toString", "()java.lang.String", "", 1);
        Mockingbird.setReturnValue(false, Mockingbird.getProxyObject(StringBuilder.class), "toString", "()java.lang.String", "", 1);
        Mockingbird.setReturnValue(false, logUtil, "showLog", "(com.huawei.ism.openapi.common.keydeifines.EnumDefine$LOG_TYPE_E,java.lang.String)void", null, 1);
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils2);
        Mockingbird.setReturnValue(false, openApiUtils2, "composeFromMap", "(org.json.JSONObject,java.util.Map)void", null, 1);
        RestManager restManager = (RestManager) Mockingbird.getProxyObject(RestManager.class);
        Mockingbird.replaceObjectForRecording(RestManager.class, "<init>(java.lang.Class,com.huawei.ism.openapi.common.commu.rest.RestRequestHandler,java.lang.String,java.util.Map,org.json.JSONObject)", restManager);
        Mockingbird.setReturnValue(restManager.getPostRequestMO(), null);
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        SnapshotMO result = snapshotHandlerImpl.create(snapshotMO);
        assertNull("result", result);
    }
    
    public void testDeleteWithAggressiveMocks() throws Throwable {
        storeStaticField(MOType.class, "SNAPSHOT");
        SnapshotHandlerImpl snapshotHandlerImpl = (SnapshotHandlerImpl) Mockingbird.getProxyObject(SnapshotHandlerImpl.class, true);
        OpenApiUtils openApiUtils = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        MOType mOType = (MOType) Mockingbird.getProxyObject(MOType.class);
        setPrivateField(snapshotHandlerImpl, "deviceID", "");
        setPrivateField(snapshotHandlerImpl, "restRequestHandler", null);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils);
        setPrivateField(MOType.class, "SNAPSHOT", mOType);
        setPrivateField(mOType, "value", new Integer(0));
        Mockingbird.setReturnValue(false, openApiUtils, "composeRelativeUri", "(java.lang.String[])java.lang.String", "", 1);
        HashMap hashMap = (HashMap) Mockingbird.getProxyObject(HashMap.class);
        Mockingbird.replaceObjectForRecording(HashMap.class, "<init>()", hashMap);
        Mockingbird.setReturnValue(false, hashMap, "put", "(java.lang.Object,java.lang.Object)java.lang.Object", null, 1);
        Mockingbird.setReturnValue(false, hashMap, "put", "(java.lang.Object,java.lang.Object)java.lang.Object", new Object[] {"ID", ""}, null, 1);
        RestManager restManager = (RestManager) Mockingbird.getProxyObject(RestManager.class);
        Mockingbird.replaceObjectForRecording(RestManager.class, "<init>(java.lang.Class,com.huawei.ism.openapi.common.commu.rest.RestRequestHandler,java.lang.String,java.util.Map,org.json.JSONObject)", restManager);
        Mockingbird.setReturnValue(restManager.getDelRequestMO(), null);
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        snapshotHandlerImpl.delete("");
        assertEquals("snapshotHandlerImpl.deviceID", "", getPrivateField(snapshotHandlerImpl, "deviceID"));
        assertNull("snapshotHandlerImpl.restRequestHandler", getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
    }
    
    public void testGetBatch() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImplDeviceID");
        SnapshotQuery cond = new SnapshotQuery(new SnapshotMO(new MO()), 100L, 1000L);
        SnapshotIterator batch = snapshotHandlerImpl.getBatch(cond);
        SnapshotIterator result = snapshotHandlerImpl.getBatch(cond);
        assertSame("result", batch, result);
    }
    
    public void testGetBatch1() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImplDeviceID");
        SnapshotIterator result = snapshotHandlerImpl.getBatch(new SnapshotQuery(new SnapshotMO(new MO()), 100L, 1000L));
        assertSame("snapshotHandlerImpl.snapshotIterator", result, getPrivateField(snapshotHandlerImpl, "snapshotIterator"));
        assertEquals("result.getConcretFilterHeaders().length", 5, result.getConcretFilterHeaders().length);
    }
    
    public void testGetWithAggressiveMocks() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = (SnapshotHandlerImpl) Mockingbird.getProxyObject(SnapshotHandlerImpl.class, true);
        OpenApiUtils openApiUtils = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        setPrivateField(snapshotHandlerImpl, "deviceID", "");
        setPrivateField(snapshotHandlerImpl, "restRequestHandler", null);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils);
        Mockingbird.setReturnValue(false, openApiUtils, "composeRelativeUri", "(java.lang.String[])java.lang.String", "", 1);
        HashMap hashMap = (HashMap) Mockingbird.getProxyObject(HashMap.class);
        Mockingbird.replaceObjectForRecording(HashMap.class, "<init>()", hashMap);
        Mockingbird.setReturnValue(false, hashMap, "put", "(java.lang.Object,java.lang.Object)java.lang.Object", new Object[] {"ID", ""}, null, 1);
        RestManager restManager = (RestManager) Mockingbird.getProxyObject(RestManager.class);
        Mockingbird.replaceObjectForRecording(RestManager.class, "<init>(java.lang.Class,com.huawei.ism.openapi.common.commu.rest.RestRequestHandler,java.lang.String,java.util.Map,org.json.JSONObject)", restManager);
        Mockingbird.setReturnValue(restManager.getGetRequestMO(), null);
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        SnapshotMO result = snapshotHandlerImpl.get("");
        assertNull("result", result);
    }
    
    public void testModifyWithAggressiveMocks() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = (SnapshotHandlerImpl) Mockingbird.getProxyObject(SnapshotHandlerImpl.class, true);
        SnapshotMO snapshotMO = (SnapshotMO) Mockingbird.getProxyObject(SnapshotMO.class);
        MO mO = (MO) Mockingbird.getProxyObject(MO.class);
        OpenApiUtils openApiUtils = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        OpenApiUtils openApiUtils2 = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        setPrivateField(snapshotHandlerImpl, "deviceID", "");
        setPrivateField(snapshotHandlerImpl, "restRequestHandler", null);
        setPrivateField(snapshotMO, "mo", mO);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils);
        setPrivateField(mO, "properties", null);
        Mockingbird.setReturnValue(snapshotMO.getId(), "");
        Mockingbird.setReturnValue(false, openApiUtils, "composeRelativeUri", "(java.lang.String[])java.lang.String", "", 1);
        Mockingbird.replaceObjectForRecording(JSONObject.class, "<init>()", Mockingbird.getProxyObject(JSONObject.class));
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils2);
        Mockingbird.setReturnValue(false, openApiUtils2, "composeFromMap", "(org.json.JSONObject,java.util.Map)void", null, 1);
        RestManager restManager = (RestManager) Mockingbird.getProxyObject(RestManager.class);
        Mockingbird.replaceObjectForRecording(RestManager.class, "<init>(java.lang.Class,com.huawei.ism.openapi.common.commu.rest.RestRequestHandler,java.lang.String,java.util.Map,org.json.JSONObject)", restManager);
        Mockingbird.setReturnValue(restManager.getPutRequestMO(), null);
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        snapshotHandlerImpl.modify(snapshotMO);
        assertEquals("snapshotHandlerImpl.deviceID", "", getPrivateField(snapshotHandlerImpl, "deviceID"));
        assertNull("snapshotHandlerImpl.restRequestHandler", getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
    }
    
    public void testRollbackHyperImageWithAggressiveMocks() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = (SnapshotHandlerImpl) Mockingbird.getProxyObject(SnapshotHandlerImpl.class, true);
        SnapshotMO snapshotMO = (SnapshotMO) Mockingbird.getProxyObject(SnapshotMO.class);
        OpenApiUtils openApiUtils = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        EnumDefine.SpeedLevelE speedLevelE = (EnumDefine.SpeedLevelE) Mockingbird.getProxyObject(EnumDefine.SpeedLevelE.class);
        setPrivateField(snapshotHandlerImpl, "deviceID", "");
        setPrivateField(snapshotHandlerImpl, "restRequestHandler", null);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils);
        setPrivateField(speedLevelE, "value", new Integer(0));
        Mockingbird.setReturnValue(false, openApiUtils, "composeRelativeUri", "(java.lang.String[])java.lang.String", "", 1);
        JSONObject jSONObject = (JSONObject) Mockingbird.getProxyObject(JSONObject.class);
        Mockingbird.replaceObjectForRecording(JSONObject.class, "<init>()", jSONObject);
        Mockingbird.setReturnValue(snapshotMO.getId(), "");
        Mockingbird.setReturnValue(false, jSONObject, "put", "(java.lang.String,java.lang.Object)org.json.JSONObject", null, 1);
        Mockingbird.setReturnValue(snapshotMO.getRollbackSpeed(), speedLevelE);
        Mockingbird.setReturnValue(jSONObject.put("ROLLBACKSPEED", 0), null);
        RestManager restManager = (RestManager) Mockingbird.getProxyObject(RestManager.class);
        Mockingbird.replaceObjectForRecording(RestManager.class, "<init>(java.lang.Class,com.huawei.ism.openapi.common.commu.rest.RestRequestHandler,java.lang.String,java.util.Map,org.json.JSONObject)", restManager);
        Mockingbird.setReturnValue(restManager.getPutRequestMO(), null);
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        snapshotHandlerImpl.rollbackHyperImage(snapshotMO);
        assertEquals("snapshotHandlerImpl.deviceID", "", getPrivateField(snapshotHandlerImpl, "deviceID"));
        assertNull("snapshotHandlerImpl.restRequestHandler", getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
    }
    
    public void testCreateThrowsApiException() throws Throwable {
        try {
            new SnapshotHandlerImpl(null, "testSnapshotHandlerImplDeviceID").create(null);
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
        }
    }
    
    public void testCreateThrowsApiExceptionWithAggressiveMocks() throws Throwable {
        storeStaticField(ConstantsDefine.ExceptionConstant.class, "JASONEXPMSG");
        storeStaticField(MOType.class, "HOST");
        SnapshotHandlerImpl snapshotHandlerImpl = (SnapshotHandlerImpl) Mockingbird.getProxyObject(SnapshotHandlerImpl.class, true);
        OpenApiUtils openApiUtils = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        MOType mOType = (MOType) Mockingbird.getProxyObject(MOType.class);
        JSONException jSONException = (JSONException) Mockingbird.getProxyObject(JSONException.class);
        ApiMessage apiMessage = (ApiMessage) Mockingbird.getProxyObject(ApiMessage.class);
        setPrivateField(snapshotHandlerImpl, "deviceID", "");
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils);
        setPrivateField(MOType.class, "HOST", mOType);
        setPrivateField(mOType, "value", new Integer(0));
        setPrivateField(ConstantsDefine.ExceptionConstant.class, "JASONEXPMSG", apiMessage);
        Mockingbird.setReturnValue(false, openApiUtils, "composeRelativeUri", "(java.lang.String[])java.lang.String", "", 1);
        JSONObject jSONObject = (JSONObject) Mockingbird.getProxyObject(JSONObject.class);
        Mockingbird.replaceObjectForRecording(JSONObject.class, "<init>()", jSONObject);
        Mockingbird.setException(jSONObject.put("TYPE", 0), jSONException);
        Mockingbird.setReturnValue(jSONException.getMessage(), "");
        Mockingbird.replaceObjectForRecording(ApiException.class, "<init>(com.huawei.ism.openapi.common.exception.ApiMessage,java.lang.Exception)", Mockingbird.getProxyObject(ApiException.class));
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        try {
            snapshotHandlerImpl.create(null);
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("snapshotHandlerImpl.deviceID", "", getPrivateField(snapshotHandlerImpl, "deviceID"));
            assertNull("snapshotHandlerImpl.restRequestHandler", getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
        }
    }
    
    public void testCreateThrowsIllegalArgumentException() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImpl\rDeviceID");
        try {
            snapshotHandlerImpl.create(null);
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
        }
    }
    
    public void testCreateThrowsIllegalArgumentException1() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImpl\rDeviceID");
        try {
            snapshotHandlerImpl.create(new SnapshotMO(new MO()));
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
        }
    }
    
    public void testCreateThrowsNullPointerException() throws Throwable {
        RestRequestHandler restRequestHandler = new RestRequestHandler("testSnapshotHandlerImplIp", 100);
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(restRequestHandler, "testSnapshotHandlerImplDeviceID");
        Mockingbird.enterRecordingMode();
        Object postRequestMO = ((RestManager) Mockingbird.getProxyObject(RestManager.class)).getPostRequestMO();
        Mockingbird.setException(true, postRequestMO, (Throwable) Mockingbird.getProxyObject(NullPointerException.class));
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        try {
            snapshotHandlerImpl.create(null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertEquals("snapshotHandlerImpl.deviceID", "testSnapshotHandlerImplDeviceID", getPrivateField(snapshotHandlerImpl, "deviceID"));
            assertSame("snapshotHandlerImpl.restRequestHandler", restRequestHandler, getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
        }
    }
    
    public void testCreateThrowsNullPointerException1() throws Throwable {
        RestRequestHandler restRequestHandler = new RestRequestHandler("testSnapshotHandlerImplIp", 100);
        JSONObject jsonBody = new JSONObject();
        jsonBody.put("testSnapshotHandlerImplKey", 100.0);
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(restRequestHandler, "testSnapshotHandlerImplDeviceID");
        SnapshotMO mo = new SnapshotMO(new MO(jsonBody));
        Mockingbird.enterRecordingMode();
        ((OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class)).composeFromMap(null, null);
        Mockingbird.setExceptionForVoid(true, (Throwable) Mockingbird.getProxyObject(NullPointerException.class));
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        try {
            snapshotHandlerImpl.create(mo);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertEquals("snapshotHandlerImpl.deviceID", "testSnapshotHandlerImplDeviceID", getPrivateField(snapshotHandlerImpl, "deviceID"));
            assertSame("snapshotHandlerImpl.restRequestHandler", restRequestHandler, getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
        }
    }
    
    public void testCreateThrowsNullPointerException2() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImplDeviceID");
        try {
            snapshotHandlerImpl.create(new SnapshotMO((MO) null));
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(SnapshotHandlerImpl.class, ex);
        }
    }
    
    public void testDeleteThrowsApiException() throws Throwable {
        try {
            new SnapshotHandlerImpl(null, "testSnapshotHandlerImplDeviceID").delete("testSnapshotHandlerImplSnapShotID");
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
        }
    }
    
    public void testDeleteThrowsIllegalArgumentException() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImplDeviceID");
        try {
            snapshotHandlerImpl.delete("testSnapshotHandlerImpl\rSnapShotID");
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
        }
    }
    
    public void testDeleteThrowsNullPointerException() throws Throwable {
        RestRequestHandler restRequestHandler = new RestRequestHandler("testSnapshotHandlerImplIp", 100);
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(restRequestHandler, "testSnapshotHandlerImplDeviceID");
        Mockingbird.enterRecordingMode();
        Mockingbird.setException(true, ((RestManager) Mockingbird.getProxyObject(RestManager.class)).getDelRequestMO(), (Throwable) Mockingbird.getProxyObject(NullPointerException.class));
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        try {
            snapshotHandlerImpl.delete("testSnapshotHandlerImplSnapShotID");
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertEquals("snapshotHandlerImpl.deviceID", "testSnapshotHandlerImplDeviceID", getPrivateField(snapshotHandlerImpl, "deviceID"));
            assertSame("snapshotHandlerImpl.restRequestHandler", restRequestHandler, getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
        }
    }
    
    public void testGetThrowsApiException() throws Throwable {
        try {
            new SnapshotHandlerImpl(null, "testSnapshotHandlerImplDeviceID").get("testSnapshotHandlerImplSnapshotID");
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
        }
    }
    
    public void testGetThrowsIllegalArgumentException() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImpl\rDeviceID");
        try {
            snapshotHandlerImpl.get("testSnapshotHandlerImplSnapshotID");
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
        }
    }
    
    public void testGetThrowsNullPointerException() throws Throwable {
        RestRequestHandler restRequestHandler = new RestRequestHandler("testSnapshotHandlerImplIp", 100);
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(restRequestHandler, "testSnapshotHandlerImplDeviceID");
        Mockingbird.enterRecordingMode();
        Mockingbird.setException(true, ((RestManager) Mockingbird.getProxyObject(RestManager.class)).getGetRequestMO(), (Throwable) Mockingbird.getProxyObject(NullPointerException.class));
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        try {
            snapshotHandlerImpl.get("testSnapshotHandlerImplSnapshotID");
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertEquals("snapshotHandlerImpl.deviceID", "testSnapshotHandlerImplDeviceID", getPrivateField(snapshotHandlerImpl, "deviceID"));
            assertSame("snapshotHandlerImpl.restRequestHandler", restRequestHandler, getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
        }
    }
    
    public void testModifyThrowsApiException() throws Throwable {
        try {
            new SnapshotHandlerImpl(null, "testSnapshotHandlerImplDeviceID").modify(null);
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
        }
    }
    
    public void testModifyThrowsIllegalArgumentException() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImpl\rDeviceID");
        SnapshotMO mo = new SnapshotMO(new MO());
        try {
            snapshotHandlerImpl.modify(mo);
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
            assertNull("mo.getDescription()", mo.getDescription());
        }
    }
    
    public void testModifyThrowsNullPointerException() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImplDeviceID");
        SnapshotMO mo = new SnapshotMO(new MO());
        Mockingbird.enterRecordingMode();
        Mockingbird.setException(true, ((RestManager) Mockingbird.getProxyObject(RestManager.class)).getPutRequestMO(), (Throwable) Mockingbird.getProxyObject(NullPointerException.class));
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        try {
            snapshotHandlerImpl.modify(mo);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("mo.getDescription()", mo.getDescription());
        }
    }
    
    public void testModifyThrowsNullPointerException1() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(null, "testSnapshotHandlerImplDeviceID");
        MO mo = new MO(new JSONObject());
        Map propertyMap = new HashMap(100, 100.0F);
        propertyMap.put((Object) null, "");
        mo.setProperty((Map) propertyMap);
        SnapshotMO mo2 = new SnapshotMO(mo);
        try {
            snapshotHandlerImpl.modify(mo2);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(OpenApiUtils.class, ex);
            assertNull("mo2.getDescription()", mo2.getDescription());
        }
    }
    
    public void testModifyThrowsNullPointerException2() throws Throwable {
        SnapshotMO mo = new SnapshotMO((MO) null);
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImplDeviceID");
        try {
            snapshotHandlerImpl.modify(mo);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(SnapshotMO.class, ex);
        }
    }
    
    public void testRollbackHyperImageThrowsApiException() throws Throwable {
        try {
            new SnapshotHandlerImpl(null, "testSnapshotHandlerImplDeviceID").rollbackHyperImage(null);
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
        }
    }
    
    public void testRollbackHyperImageThrowsApiException1() throws Throwable {
        SnapshotMO mo = new SnapshotMO();
        mo.setRollbackSpeed(EnumDefine.SpeedLevelE.SPEED_LEVEL_MIDDLE);
        try {
            new SnapshotHandlerImpl(null, "testSnapshotHandlerImplDeviceID").rollbackHyperImage(mo);
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
            assertNull("mo.getDescription()", mo.getDescription());
        }
    }
    
    public void testRollbackHyperImageThrowsApiException2() throws Throwable {
        SnapshotMO mo = new SnapshotMO(new MO());
        try {
            new SnapshotHandlerImpl(null, "testSnapshotHandlerImplDeviceID").rollbackHyperImage(mo);
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
            assertNull("mo.getDescription()", mo.getDescription());
        }
    }
    
    public void testRollbackHyperImageThrowsApiExceptionWithAggressiveMocks() throws Throwable {
        storeStaticField(ConstantsDefine.ExceptionConstant.class, "JASONEXPMSG");
        SnapshotHandlerImpl snapshotHandlerImpl = (SnapshotHandlerImpl) Mockingbird.getProxyObject(SnapshotHandlerImpl.class, true);
        SnapshotMO snapshotMO = (SnapshotMO) Mockingbird.getProxyObject(SnapshotMO.class);
        OpenApiUtils openApiUtils = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        JSONException jSONException = (JSONException) Mockingbird.getProxyObject(JSONException.class);
        ApiMessage apiMessage = (ApiMessage) Mockingbird.getProxyObject(ApiMessage.class);
        setPrivateField(snapshotHandlerImpl, "deviceID", "");
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils);
        setPrivateField(ConstantsDefine.ExceptionConstant.class, "JASONEXPMSG", apiMessage);
        Mockingbird.setReturnValue(false, openApiUtils, "composeRelativeUri", "(java.lang.String[])java.lang.String", "", 1);
        JSONObject jSONObject = (JSONObject) Mockingbird.getProxyObject(JSONObject.class);
        Mockingbird.replaceObjectForRecording(JSONObject.class, "<init>()", jSONObject);
        Mockingbird.setReturnValue(snapshotMO.getId(), "");
        Mockingbird.setException(false, jSONObject, "put", "(java.lang.String,java.lang.Object)org.json.JSONObject", jSONException, 1);
        Mockingbird.setReturnValue(jSONException.getMessage(), "");
        Mockingbird.replaceObjectForRecording(ApiException.class, "<init>(com.huawei.ism.openapi.common.exception.ApiMessage,java.lang.Exception)", Mockingbird.getProxyObject(ApiException.class));
        Mockingbird.enterTestMode(SnapshotHandlerImpl.class);
        try {
            snapshotHandlerImpl.rollbackHyperImage(snapshotMO);
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("snapshotHandlerImpl.deviceID", "", getPrivateField(snapshotHandlerImpl, "deviceID"));
            assertNull("snapshotHandlerImpl.restRequestHandler", getPrivateField(snapshotHandlerImpl, "restRequestHandler"));
        }
    }
    
    public void testRollbackHyperImageThrowsIllegalArgumentException() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImpl\rIp", 100), "testSnapshotHandlerImplDeviceID");
        try {
            snapshotHandlerImpl.rollbackHyperImage(null);
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
        }
    }
    
    public void testRollbackHyperImageThrowsNullPointerException() throws Throwable {
        SnapshotHandlerImpl snapshotHandlerImpl = new SnapshotHandlerImpl(new RestRequestHandler("testSnapshotHandlerImplIp", 100), "testSnapshotHandlerImplDeviceID");
        SnapshotMO mo = new SnapshotMO((MO) null);
        try {
            snapshotHandlerImpl.rollbackHyperImage(mo);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(SnapshotMO.class, ex);
        }
    }
}

