/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:28:43
 * Time to generate: 00:11.953 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.disk.DiskQuery:d2b9dc0b5412c56dba4655c1eb70c536
 * agitar.src.md5=com.huawei.ism.openapi.common.batchquery.QueryBase:f63d4febf06763dd4c3d64f304793100
 *
 */

package com.huawei.ism.openapi.disk;

import com.agitar.lib.junit.AgitarTestCase;
import org.json.JSONObject;

public class DiskQueryAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return DiskQuery.class;
    }
    
    public void testConstructor() throws Throwable {
        DiskMO mo = new DiskMO();
        DiskQuery diskQuery = new DiskQuery(mo, 100L, 1000L);
        assertEquals("diskQuery.getCount()", 1000L, diskQuery.getCount());
        assertEquals("diskQuery.getBeginIndex()", 100L, diskQuery.getBeginIndex());
        assertSame("diskQuery.mo", mo, getPrivateField(diskQuery, "mo"));
    }
    
    public void testGetDiskMO() throws Throwable {
        DiskMO mo = new DiskMO();
        DiskMO result = new DiskQuery(mo, 100L, 1000L).getDiskMO();
        assertSame("result", mo, result);
    }
    
    public void testGetDiskMO1() throws Throwable {
        DiskQuery diskQuery = new DiskQuery(new DiskMO(new JSONObject()), 100L, 1000L);
        diskQuery.setQueryDiskMO(null);
        DiskMO result = diskQuery.getDiskMO();
        assertNull("result", result);
    }
    
    public void testSetQueryDiskMO() throws Throwable {
        DiskMO mo = new DiskMO();
        DiskQuery diskQuery = new DiskQuery(mo, 100L, 1000L);
        diskQuery.setQueryDiskMO(mo);
        assertSame("diskQuery.mo", mo, getPrivateField(diskQuery, "mo"));
    }
}

