/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:37:05
 * Time to generate: 00:58.359 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.nas.nfsauthclient.NFSShareAuthClientIterator:674331c0100be239a1c55e818a1de601
 * agitar.src.md5=com.huawei.ism.openapi.common.batchquery.ApiIterator:592fbb87e71ade6d26e6fe9200d66392
 *
 */

package com.huawei.ism.openapi.nas.nfsauthclient;

import com.agitar.lib.junit.AgitarTestCase;
import com.agitar.lib.mockingbird.Mockingbird;
import com.huawei.ism.openapi.common.commu.rest.RestManager;
import com.huawei.ism.openapi.common.commu.rest.RestRequestHandler;
import com.huawei.ism.openapi.common.exception.ApiException;
import com.huawei.ism.openapi.common.model.MO;
import com.huawei.ism.openapi.common.model.MOType;
import com.huawei.ism.openapi.common.utils.OpenApiUtils;
import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.apache.http.client.ClientProtocolException;

public class NFSShareAuthClientIteratorAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return NFSShareAuthClientIterator.class;
    }
    
    public void testConstructor() throws Throwable {
        RestRequestHandler restRequestHandler = new RestRequestHandler("testNFSShareAuthClientIteratorIp", 100);
        NFSShareAuthClientQuery queryCondition = new NFSShareAuthClientQuery(null, 100L, 1000L);
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(restRequestHandler, "testNFSShareAuthClientIteratorDeviceID", queryCondition);
        assertNull("nFSShareAuthClientIterator.headerMap", getPrivateField(nFSShareAuthClientIterator, "headerMap"));
        assertEquals("nFSShareAuthClientIterator.totalCount", 0L, ((Number) getPrivateField(nFSShareAuthClientIterator, "totalCount")).longValue());
        assertSame("nFSShareAuthClientIterator.restRequestHandler", restRequestHandler, getPrivateField(nFSShareAuthClientIterator, "restRequestHandler"));
        assertEquals("nFSShareAuthClientIterator.curIndex", 100L, ((Number) getPrivateField(nFSShareAuthClientIterator, "curIndex")).longValue());
        assertEquals("nFSShareAuthClientIterator.deviceID", "testNFSShareAuthClientIteratorDeviceID", getPrivateField(nFSShareAuthClientIterator, "deviceID"));
        assertSame("nFSShareAuthClientIterator.getQuery()", queryCondition, nFSShareAuthClientIterator.getQuery());
    }
    
    public void testGetConcretCountWithAggressiveMocks() throws Throwable {
        storeStaticField(MOType.class, "SNAS_NFS_SHARE_AUTH_CLIENT");
        NFSShareAuthClientIterator nFSShareAuthClientIterator = (NFSShareAuthClientIterator) Mockingbird.getProxyObject(NFSShareAuthClientIterator.class, true);
        OpenApiUtils openApiUtils = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        MOType mOType = (MOType) Mockingbird.getProxyObject(MOType.class);
        NFSShareAuthClientMO nFSShareAuthClientMO = (NFSShareAuthClientMO) Mockingbird.getProxyObject(NFSShareAuthClientMO.class);
        MO mO = (MO) Mockingbird.getProxyObject(MO.class);
        setPrivateField(nFSShareAuthClientIterator, "deviceID", "");
        setPrivateField(nFSShareAuthClientIterator, "queryCondition", null);
        setPrivateField(nFSShareAuthClientIterator, "restRequestHandler", null);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils);
        setPrivateField(MOType.class, "SNAS_NFS_SHARE_AUTH_CLIENT", mOType);
        setPrivateField(mOType, "value", new Integer(0));
        setPrivateField(nFSShareAuthClientMO, "mo", mO);
        Mockingbird.setReturnValue(false, openApiUtils, "composeRelativeUri", "(java.lang.String[])java.lang.String", "", 1);
        HashMap hashMap = (HashMap) Mockingbird.getProxyObject(HashMap.class);
        Mockingbird.replaceObjectForRecording(HashMap.class, "<init>()", hashMap);
        Mockingbird.setReturnValue(false, hashMap, "put", "(java.lang.Object,java.lang.Object)java.lang.Object", null, 1);
        RestManager restManager = (RestManager) Mockingbird.getProxyObject(RestManager.class);
        Mockingbird.replaceObjectForRecording(RestManager.class, "<init>(java.lang.Class,com.huawei.ism.openapi.common.commu.rest.RestRequestHandler,java.lang.String,java.util.Map,org.json.JSONObject)", restManager);
        Mockingbird.setReturnValue(restManager.getGetRequestMO(), nFSShareAuthClientMO);
        Mockingbird.setReturnValue(false, mO, "getProperty", "(java.lang.Object)java.lang.Object", "", 1);
        Mockingbird.setReturnValue(true, Long.class, "valueOf", "(java.lang.String)java.lang.Long", new Object[] {""}, new Long(0L), 1);
        Mockingbird.enterTestMode(NFSShareAuthClientIterator.class);
        long result = nFSShareAuthClientIterator.getConcretCount();
        assertEquals("result", 0L, result);
        assertNull("nFSShareAuthClientIterator.headerMap", getPrivateField(nFSShareAuthClientIterator, "headerMap"));
    }
    
    public void testGetConcretFilterHeaders() throws Throwable {
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(null, "testNFSShareAuthClientIteratorDeviceID", new NFSShareAuthClientQuery(new NFSShareAuthClientMO(), 100L, 1000L));
        String[] result = nFSShareAuthClientIterator.getConcretFilterHeaders();
        assertEquals("result.length", 4, result.length);
        assertEquals("result[0]", "ID", result[0]);
    }
    
    public void testGetConcretMoMap() throws Throwable {
        NFSShareAuthClientMO mo = new NFSShareAuthClientMO(null);
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(new RestRequestHandler("testNFSShareAuthClientIteratorIp", 100), "testNFSShareAuthClientIteratorDeviceID", new NFSShareAuthClientQuery(mo, 100L, 1000L));
        ConcurrentHashMap result = (ConcurrentHashMap) nFSShareAuthClientIterator.getConcretMoMap(mo);
        assertEquals("result.size()", 0, result.size());
    }
    
    public void testGetConcretMoMap1() throws Throwable {
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(new RestRequestHandler("testNFSShareAuthClientIteratorIp", 100), "testNFSShareAuthClientIteratorDeviceID", new NFSShareAuthClientQuery(new NFSShareAuthClientMO(null), 100L, 1000L));
        Map result = nFSShareAuthClientIterator.getConcretMoMap((NFSShareAuthClientMO) null);
        assertNull("result", result);
    }
    
    public void testGetConcretBatchNextThrowsApiException() throws Throwable {
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(null, "testNFSShareAuthClientIteratorDeviceID", new NFSShareAuthClientQuery(new NFSShareAuthClientMO(), 100L, 1000L));
        try {
            nFSShareAuthClientIterator.getConcretBatchNext();
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
            assertEquals("nFSShareAuthClientIterator.headerMap.size()", 0, ((Map) getPrivateField(nFSShareAuthClientIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretBatchNextThrowsIllegalArgumentException() throws Throwable {
        NFSShareAuthClientMO mo = new NFSShareAuthClientMO(null);
        NFSShareAuthClientQuery queryCondition = new NFSShareAuthClientQuery(mo, 100L, 1000L);
        mo.setAllSquash(new Integer(0));
        mo.setSharePath("testNFSShareAuthClientIteratorSharePath");
        mo.setAccessName("testNFSShareAuthClientIteratorAccessName");
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(new RestRequestHandler("testNFSShareAuthClientIterator\rIp", 100), "testNFSShareAuthClientIteratorDeviceID", queryCondition);
        try {
            nFSShareAuthClientIterator.getConcretBatchNext();
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
            assertEquals("nFSShareAuthClientIterator.headerMap.size()", 1, ((Map) getPrivateField(nFSShareAuthClientIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretBatchNextThrowsNullPointerException() throws Throwable {
        NFSShareAuthClientMO mo = new NFSShareAuthClientMO(null);
        mo.setAllSquash(new Integer(0));
        mo.setSharePath("testNFSShareAuthClientIteratorSharePath");
        mo.setAccessName("testNFSShareAuthClientIteratorAccessName");
        NFSShareAuthClientQuery queryCondition = new NFSShareAuthClientQuery(new NFSShareAuthClientMO(), 100L, 1000L);
        queryCondition.setNFSShareAuthClientMO(mo);
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(new RestRequestHandler("testNFSShareAuthClientIteratorIp", 100), "testNFSShareAuthClientIteratorDeviceID", queryCondition);
        Mockingbird.enterRecordingMode();
        Object getRequestMOList = ((RestManager) Mockingbird.getProxyObject(RestManager.class)).getGetRequestMOList();
        Mockingbird.setException(true, getRequestMOList, (Throwable) Mockingbird.getProxyObject(NullPointerException.class));
        Mockingbird.enterTestMode(NFSShareAuthClientIterator.class);
        try {
            nFSShareAuthClientIterator.getConcretBatchNext();
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertEquals("nFSShareAuthClientIterator.headerMap.size()", 1, ((Map) getPrivateField(nFSShareAuthClientIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretCountThrowsApiException() throws Throwable {
        NFSShareAuthClientMO mo = new NFSShareAuthClientMO(null);
        mo.setAllSquash(new Integer(0));
        mo.setSharePath("testNFSShareAuthClientIteratorSharePath");
        mo.setAccessName("testNFSShareAuthClientIteratorAccessName");
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(null, "testNFSShareAuthClientIteratorDeviceID", new NFSShareAuthClientQuery(mo, 100L, 1000L));
        try {
            nFSShareAuthClientIterator.getConcretCount();
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
            assertEquals("nFSShareAuthClientIterator.headerMap.size()", 1, ((Map) getPrivateField(nFSShareAuthClientIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretCountThrowsApiException1() throws Throwable {
        NFSShareAuthClientQuery queryCondition = new NFSShareAuthClientQuery(new NFSShareAuthClientMO(), 100L, 1000L);
        callPrivateMethod("com.huawei.ism.openapi.common.batchquery.QueryBase", "setConcretQueryMO", new Class[] {Object.class}, queryCondition, new Object[] {new NFSShareAuthClientMO()});
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(new RestRequestHandler("/deviceManager/rest", 100), "testNFSShareAuthClientIteratorDeviceID", queryCondition);
        try {
            nFSShareAuthClientIterator.getConcretCount();
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "URI does not specify a valid host name: https:///deviceManager/rest:100/deviceManager/rest/testNFSShareAuthClientIteratorDeviceID/SNAS_NFS_SHARE_AUTH_CLIENT/count?TYPE=16409", ex.getMessage());
            assertThrownBy(RestRequestHandler.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "URI does not specify a valid host name: https:///deviceManager/rest:100/deviceManager/rest/testNFSShareAuthClientIteratorDeviceID/SNAS_NFS_SHARE_AUTH_CLIENT/count?TYPE=16409", ex.getErrMessage().getErrorDescription());
            assertEquals("ex.getException().getClass()", ClientProtocolException.class, ex.getException().getClass());
            assertEquals("nFSShareAuthClientIterator.headerMap.size()", 0, ((Map) getPrivateField(nFSShareAuthClientIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretCountThrowsIllegalArgumentException() throws Throwable {
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(new RestRequestHandler("testNFSShareAuthClientIterator\rIp", 100), "testNFSShareAuthClientIteratorDeviceID", new NFSShareAuthClientQuery(new NFSShareAuthClientMO(), 100L, 1000L));
        try {
            nFSShareAuthClientIterator.getConcretCount();
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
            assertEquals("nFSShareAuthClientIterator.headerMap.size()", 0, ((Map) getPrivateField(nFSShareAuthClientIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretCountThrowsNullPointerException() throws Throwable {
        NFSShareAuthClientMO mo = new NFSShareAuthClientMO(null);
        NFSShareAuthClientQuery queryCondition = new NFSShareAuthClientQuery(mo, 100L, 1000L);
        mo.setAllSquash(new Integer(0));
        mo.setSharePath("testNFSShareAuthClientIteratorSharePath");
        mo.setAccessName("testNFSShareAuthClientIteratorAccessName");
        NFSShareAuthClientIterator nFSShareAuthClientIterator = new NFSShareAuthClientIterator(new RestRequestHandler("testNFSShareAuthClientIteratorIp", 100), "testNFSShareAuthClientIteratorDeviceID", queryCondition);
        Mockingbird.enterRecordingMode();
        Mockingbird.setException(true, ((RestManager) Mockingbird.getProxyObject(RestManager.class)).getGetRequestMO(), (Throwable) Mockingbird.getProxyObject(NullPointerException.class));
        Mockingbird.enterTestMode(NFSShareAuthClientIterator.class);
        try {
            nFSShareAuthClientIterator.getConcretCount();
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertEquals("nFSShareAuthClientIterator.headerMap.size()", 1, ((Map) getPrivateField(nFSShareAuthClientIterator, "headerMap")).size());
        }
    }
}

