/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:25:41
 * Time to generate: 00:09.843 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.common.exception.ApiMessage:05c6baeb1c12a0cb0588eb811b105ab3
 *
 */

package com.huawei.ism.openapi.common.exception;

import com.agitar.lib.junit.AgitarTestCase;

public class ApiMessageAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return ApiMessage.class;
    }
    
    public void testConstructor() throws Throwable {
        ApiMessage apiMessage = new ApiMessage(100L, "testApiMessageErrDescription", "testApiMessageErrSuggestion");
        assertEquals("apiMessage.getErrorCode()", 100L, apiMessage.getErrorCode());
        assertEquals("apiMessage.getErrorDescription()", "testApiMessageErrDescription", apiMessage.getErrorDescription());
        assertEquals("apiMessage.getErrorSuggestion()", "testApiMessageErrSuggestion", apiMessage.getErrorSuggestion());
    }
    
    public void testGetErrorCode() throws Throwable {
        ApiMessage apiMessage = new ApiMessage(0L, "testApiMessageErrDescription", "testApiMessageErrSuggestion");
        long result = apiMessage.getErrorCode();
        assertEquals("result", 0L, result);
    }
    
    public void testGetErrorCode1() throws Throwable {
        ApiMessage apiMessage = new ApiMessage(100L, "testApiMessageErrDescription", "testApiMessageErrSuggestion");
        long result = apiMessage.getErrorCode();
        assertEquals("result", 100L, result);
    }
    
    public void testGetErrorDescription() throws Throwable {
        ApiMessage apiMessage = new ApiMessage(100L, "testApiMessageErrDescription", "testApiMessageErrSuggestion");
        String result = apiMessage.getErrorDescription();
        assertEquals("result", "testApiMessageErrDescription", result);
    }
    
    public void testGetErrorSuggestion() throws Throwable {
        ApiMessage apiMessage = new ApiMessage(100L, "testApiMessageErrDescription", "testApiMessageErrSuggestion");
        String result = apiMessage.getErrorSuggestion();
        assertEquals("result", "testApiMessageErrSuggestion", result);
    }
    
    public void testSetErrDescription() throws Throwable {
        ApiMessage apiMessage = new ApiMessage(100L, "testApiMessageErrDescription", "testApiMessageErrSuggestion");
        apiMessage.setErrDescription("testApiMessageErrDescription1");
        assertEquals("apiMessage.getErrorDescription()", "testApiMessageErrDescription1", apiMessage.getErrorDescription());
    }
    
    public void testSetErrSuggestion() throws Throwable {
        ApiMessage apiMessage = new ApiMessage(100L, "testApiMessageErrDescription", "testApiMessageErrSuggestion");
        apiMessage.setErrSuggestion("testApiMessageErrSuggestion");
        assertEquals("apiMessage.getErrorSuggestion()", "testApiMessageErrSuggestion", apiMessage.getErrorSuggestion());
    }
}

