/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:30:43
 * Time to generate: 01:02.265 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.fcoeport.FCoEPortIterator:0f29adce5e5a9e3bdd849d5493606a96
 * agitar.src.md5=com.huawei.ism.openapi.common.batchquery.ApiIterator:592fbb87e71ade6d26e6fe9200d66392
 *
 */

package com.huawei.ism.openapi.fcoeport;

import com.agitar.lib.junit.AgitarTestCase;
import com.agitar.lib.mockingbird.Mockingbird;
import com.huawei.ism.openapi.common.commu.rest.RestManager;
import com.huawei.ism.openapi.common.commu.rest.RestRequestHandler;
import com.huawei.ism.openapi.common.exception.ApiException;
import com.huawei.ism.openapi.common.model.MO;
import com.huawei.ism.openapi.common.model.MOType;
import com.huawei.ism.openapi.common.utils.OpenApiUtils;
import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.apache.http.client.ClientProtocolException;

public class FCoEPortIteratorAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return FCoEPortIterator.class;
    }
    
    public void testConstructor() throws Throwable {
        RestRequestHandler restRequestHandler = new RestRequestHandler("testFCoEPortIteratorIp", 100);
        FCoEPortQuery queryCondition = new FCoEPortQuery(new FCoEPortMO(), 100L, 1000L);
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(restRequestHandler, "testFCoEPortIteratorDeviceID", queryCondition);
        assertNull("fCoEPortIterator.headerMap", getPrivateField(fCoEPortIterator, "headerMap"));
        assertEquals("fCoEPortIterator.totalCount", 0L, ((Number) getPrivateField(fCoEPortIterator, "totalCount")).longValue());
        assertSame("fCoEPortIterator.restRequestHandler", restRequestHandler, getPrivateField(fCoEPortIterator, "restRequestHandler"));
        assertEquals("fCoEPortIterator.curIndex", 100L, ((Number) getPrivateField(fCoEPortIterator, "curIndex")).longValue());
        assertEquals("fCoEPortIterator.deviceID", "testFCoEPortIteratorDeviceID", getPrivateField(fCoEPortIterator, "deviceID"));
        assertSame("fCoEPortIterator.getQuery()", queryCondition, fCoEPortIterator.getQuery());
    }
    
    public void testGetConcretCountWithAggressiveMocks() throws Throwable {
        storeStaticField(MOType.class, "FCOE_PORT");
        FCoEPortIterator fCoEPortIterator = (FCoEPortIterator) Mockingbird.getProxyObject(FCoEPortIterator.class, true);
        OpenApiUtils openApiUtils = (OpenApiUtils) Mockingbird.getProxyObject(OpenApiUtils.class);
        MOType mOType = (MOType) Mockingbird.getProxyObject(MOType.class);
        FCoEPortMO fCoEPortMO = (FCoEPortMO) Mockingbird.getProxyObject(FCoEPortMO.class);
        MO mO = (MO) Mockingbird.getProxyObject(MO.class);
        setPrivateField(fCoEPortIterator, "deviceID", "");
        setPrivateField(fCoEPortIterator, "queryCondition", null);
        setPrivateField(fCoEPortIterator, "restRequestHandler", null);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(OpenApiUtils.getOpenApiUtilsInstance(), openApiUtils);
        setPrivateField(MOType.class, "FCOE_PORT", mOType);
        setPrivateField(mOType, "value", new Integer(0));
        setPrivateField(fCoEPortMO, "mo", mO);
        Mockingbird.setReturnValue(false, openApiUtils, "composeRelativeUri", "(java.lang.String[])java.lang.String", "", 1);
        HashMap hashMap = (HashMap) Mockingbird.getProxyObject(HashMap.class);
        Mockingbird.replaceObjectForRecording(HashMap.class, "<init>()", hashMap);
        Mockingbird.setReturnValue(false, hashMap, "put", "(java.lang.Object,java.lang.Object)java.lang.Object", null, 1);
        RestManager restManager = (RestManager) Mockingbird.getProxyObject(RestManager.class);
        Mockingbird.replaceObjectForRecording(RestManager.class, "<init>(java.lang.Class,com.huawei.ism.openapi.common.commu.rest.RestRequestHandler,java.lang.String,java.util.Map,org.json.JSONObject)", restManager);
        Mockingbird.setReturnValue(restManager.getGetRequestMO(), fCoEPortMO);
        Mockingbird.setReturnValue(false, mO, "getProperty", "(java.lang.Object)java.lang.Object", "", 1);
        Mockingbird.setReturnValue(true, Long.class, "valueOf", "(java.lang.String)java.lang.Long", new Long(0L), 1);
        Mockingbird.enterTestMode(FCoEPortIterator.class);
        long result = fCoEPortIterator.getConcretCount();
        assertEquals("result", 0L, result);
        assertNull("fCoEPortIterator.headerMap", getPrivateField(fCoEPortIterator, "headerMap"));
    }
    
    public void testGetConcretFilterHeaders() throws Throwable {
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(new RestRequestHandler("testFCoEPortIteratorIp", 100), "testFCoEPortIteratorDeviceID", null);
        String[] result = fCoEPortIterator.getConcretFilterHeaders();
        assertEquals("result.length", 1, result.length);
        assertEquals("result[0]", "ID", result[0]);
    }
    
    public void testGetConcretMoMap() throws Throwable {
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(new RestRequestHandler("testFCoEPortIteratorIp", 100), "testFCoEPortIteratorDeviceID", null);
        ConcurrentHashMap result = (ConcurrentHashMap) fCoEPortIterator.getConcretMoMap(new FCoEPortMO());
        assertEquals("result.size()", 1, result.size());
        assertEquals("(ConcurrentHashMap) result.get(\"TYPE\")", new Integer(252), result.get("TYPE"));
    }
    
    public void testGetConcretMoMap1() throws Throwable {
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(new RestRequestHandler("testFCoEPortIteratorIp", 100), "testFCoEPortIteratorDeviceID", null);
        Map result = fCoEPortIterator.getConcretMoMap((FCoEPortMO) null);
        assertNull("result", result);
    }
    
    public void testGetConcretBatchNextThrowsApiException() throws Throwable {
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(new RestRequestHandler("/deviceManaTger/rest", 100), "testFCoEPortIteratorDeviceID", new FCoEPortQuery(new FCoEPortMO(), 100L, 1000L));
        try {
            fCoEPortIterator.getConcretBatchNext();
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "URI does not specify a valid host name: https:///deviceManaTger/rest:100/deviceManager/rest/testFCoEPortIteratorDeviceID/FCOE_PORT?range=[100-1100]&TYPE=252", ex.getMessage());
            assertThrownBy(RestRequestHandler.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "URI does not specify a valid host name: https:///deviceManaTger/rest:100/deviceManager/rest/testFCoEPortIteratorDeviceID/FCOE_PORT?range=[100-1100]&TYPE=252", ex.getErrMessage().getErrorDescription());
            assertEquals("ex.getException().getClass()", ClientProtocolException.class, ex.getException().getClass());
            assertEquals("fCoEPortIterator.headerMap.size()", 0, ((Map) getPrivateField(fCoEPortIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretBatchNextThrowsIllegalArgumentException() throws Throwable {
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(new RestRequestHandler("testFCoEPortIterator\rIp", 100), "testFCoEPortIteratorDeviceID", new FCoEPortQuery(new FCoEPortMO(), 100L, 1000L));
        try {
            fCoEPortIterator.getConcretBatchNext();
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
            assertEquals("fCoEPortIterator.headerMap.size()", 0, ((Map) getPrivateField(fCoEPortIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretBatchNextThrowsNullPointerException() throws Throwable {
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(new RestRequestHandler("testFCoEPortIteratorIp", 100), "testFCoEPortIteratorDeviceID", new FCoEPortQuery(new FCoEPortMO(), 100L, 1000L));
        Mockingbird.enterRecordingMode();
        Object getRequestMOList = ((RestManager) Mockingbird.getProxyObject(RestManager.class)).getGetRequestMOList();
        Mockingbird.setException(true, getRequestMOList, (Throwable) Mockingbird.getProxyObject(NullPointerException.class));
        Mockingbird.enterTestMode(FCoEPortIterator.class);
        try {
            fCoEPortIterator.getConcretBatchNext();
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertEquals("fCoEPortIterator.headerMap.size()", 0, ((Map) getPrivateField(fCoEPortIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretCountThrowsApiException() throws Throwable {
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(null, "testFCoEPortIteratorDeviceID", new FCoEPortQuery(new FCoEPortMO(), 100L, 1000L));
        try {
            fCoEPortIterator.getConcretCount();
            fail("Expected ApiException to be thrown");
        } catch (ApiException ex) {
            assertEquals("ex.getMessage()", "the restRequestHandler is null", ex.getMessage());
            assertThrownBy(RestManager.class, ex);
            assertEquals("ex.getErrMessage().getErrorDescription()", "the restRequestHandler is null", ex.getErrMessage().getErrorDescription());
            assertNull("ex.getException()", ex.getException());
            assertEquals("fCoEPortIterator.headerMap.size()", 0, ((Map) getPrivateField(fCoEPortIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretCountThrowsIllegalArgumentException() throws Throwable {
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(new RestRequestHandler("testFCoEPortIterator\rIp", 100), "testFCoEPortIteratorDeviceID", new FCoEPortQuery(new FCoEPortMO(), 100L, 1000L));
        try {
            fCoEPortIterator.getConcretCount();
            fail("Expected IllegalArgumentException to be thrown");
        } catch (IllegalArgumentException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(URI.class, ex);
            assertEquals("fCoEPortIterator.headerMap.size()", 0, ((Map) getPrivateField(fCoEPortIterator, "headerMap")).size());
        }
    }
    
    public void testGetConcretCountThrowsNullPointerException() throws Throwable {
        FCoEPortIterator fCoEPortIterator = new FCoEPortIterator(new RestRequestHandler("testFCoEPortIteratorIp", 100), "testFCoEPortIteratorDeviceID", new FCoEPortQuery(new FCoEPortMO(), 100L, 1000L));
        Mockingbird.enterRecordingMode();
        Mockingbird.setException(true, ((RestManager) Mockingbird.getProxyObject(RestManager.class)).getGetRequestMO(), (Throwable) Mockingbird.getProxyObject(NullPointerException.class));
        Mockingbird.enterTestMode(FCoEPortIterator.class);
        try {
            fCoEPortIterator.getConcretCount();
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertEquals("fCoEPortIterator.headerMap.size()", 0, ((Map) getPrivateField(fCoEPortIterator, "headerMap")).size());
        }
    }
}

