/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:37:20
 * Time to generate: 00:19.672 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.nas.nfsshare.NFSShareQuery:ff015a177b8a6ded27b76698da2b0add
 * agitar.src.md5=com.huawei.ism.openapi.common.batchquery.QueryBase:f63d4febf06763dd4c3d64f304793100
 *
 */

package com.huawei.ism.openapi.nas.nfsshare;

import com.agitar.lib.junit.AgitarTestCase;
import java.util.HashMap;
import org.json.JSONObject;

public class NFSShareQueryAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return NFSShareQuery.class;
    }
    
    public void testConstructor() throws Throwable {
        NFSShareMO mo = new NFSShareMO();
        NFSShareQuery nFSShareQuery = new NFSShareQuery(mo, 100L, 1000L);
        assertEquals("nFSShareQuery.getCount()", 1000L, nFSShareQuery.getCount());
        assertEquals("nFSShareQuery.getBeginIndex()", 100L, nFSShareQuery.getBeginIndex());
        assertSame("nFSShareQuery.mo", mo, getPrivateField(nFSShareQuery, "mo"));
    }
    
    public void testSetQueryNFSShareMO() throws Throwable {
        NFSShareMO mo = new NFSShareMO(new JSONObject(new HashMap(100, 100.0F)));
        NFSShareQuery nFSShareQuery = new NFSShareQuery(mo, 100L, 1000L);
        nFSShareQuery.setQueryNFSShareMO(mo);
        assertSame("nFSShareQuery.mo", mo, getPrivateField(nFSShareQuery, "mo"));
    }
    
    public void testGetNFSShareMOThrowsStackOverflowError() throws Throwable {
        try {
            new NFSShareQuery(new NFSShareMO(), 100L, 1000L).getNFSShareMO();
            fail("Expected StackOverflowError to be thrown");
        } catch (StackOverflowError ex) {
            assertEquals("ex.getClass()", StackOverflowError.class, ex.getClass());
        }
    }
}

