/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:31:10
 * Time to generate: 00:11.422 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.nas.filesystem.FileSystemQuery:e0ea423cca6cb81f2cfefcc2f58c91b4
 * agitar.src.md5=com.huawei.ism.openapi.common.batchquery.QueryBase:f63d4febf06763dd4c3d64f304793100
 *
 */

package com.huawei.ism.openapi.nas.filesystem;

import com.agitar.lib.junit.AgitarTestCase;
import com.huawei.ism.openapi.common.model.MO;
import org.json.JSONObject;

public class FileSystemQueryAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return FileSystemQuery.class;
    }
    
    public void testConstructor() throws Throwable {
        FileSystemMO mo = new FileSystemMO();
        FileSystemQuery fileSystemQuery = new FileSystemQuery(mo, 100L, 1000L);
        assertEquals("fileSystemQuery.getCount()", 1000L, fileSystemQuery.getCount());
        assertEquals("fileSystemQuery.getBeginIndex()", 100L, fileSystemQuery.getBeginIndex());
        assertSame("fileSystemQuery.mo", mo, getPrivateField(fileSystemQuery, "mo"));
    }
    
    public void testGetFileSystemMO() throws Throwable {
        FileSystemMO result = new FileSystemQuery(null, 100L, 1000L).getFileSystemMO();
        assertNull("result", result);
    }
    
    public void testGetFileSystemMO1() throws Throwable {
        FileSystemMO mo = new FileSystemMO(new MO(new JSONObject()));
        FileSystemMO result = new FileSystemQuery(mo, 100L, 1000L).getFileSystemMO();
        assertSame("result", mo, result);
    }
    
    public void testSetQueryFileSystemMO() throws Throwable {
        FileSystemMO mo = new FileSystemMO();
        FileSystemQuery fileSystemQuery = new FileSystemQuery(mo, 100L, 1000L);
        fileSystemQuery.setQueryFileSystemMO(mo);
        assertSame("fileSystemQuery.mo", mo, getPrivateField(fileSystemQuery, "mo"));
    }
}

