/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:32:01
 * Time to generate: 00:10.750 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.hostgroup.HostGroupQuery:78548ce6bd0922d79dad38438afabfb1
 * agitar.src.md5=com.huawei.ism.openapi.common.batchquery.QueryBase:f63d4febf06763dd4c3d64f304793100
 *
 */

package com.huawei.ism.openapi.hostgroup;

import com.agitar.lib.junit.AgitarTestCase;

public class HostGroupQueryAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return HostGroupQuery.class;
    }
    
    public void testConstructor() throws Throwable {
        HostGroupMO mo = new HostGroupMO();
        HostGroupQuery hostGroupQuery = new HostGroupQuery(mo, 100L, 1000L);
        assertEquals("hostGroupQuery.getCount()", 1000L, hostGroupQuery.getCount());
        assertEquals("hostGroupQuery.getBeginIndex()", 100L, hostGroupQuery.getBeginIndex());
        assertSame("hostGroupQuery.mo", mo, getPrivateField(hostGroupQuery, "mo"));
    }
    
    public void testGetHostGroupMO() throws Throwable {
        HostGroupQuery hostGroupQuery = new HostGroupQuery(new HostGroupMO(), 100L, 1000L);
        hostGroupQuery.setHostGroupMO(null);
        HostGroupMO result = hostGroupQuery.getHostGroupMO();
        assertNull("result", result);
    }
    
    public void testGetHostGroupMO1() throws Throwable {
        HostGroupMO mo = new HostGroupMO();
        HostGroupMO result = new HostGroupQuery(mo, 100L, 1000L).getHostGroupMO();
        assertSame("result", mo, result);
    }
    
    public void testSetHostGroupMO() throws Throwable {
        HostGroupMO mo = new HostGroupMO();
        HostGroupQuery hostGroupQuery = new HostGroupQuery(mo, 100L, 1000L);
        hostGroupQuery.setHostGroupMO(mo);
        assertSame("hostGroupQuery.mo", mo, getPrivateField(hostGroupQuery, "mo"));
    }
}

