function LanguageControllerEN()
{
	this.language = {
		buttons : {
			"loginBtn" : "Login",
			"getDeviceListBtn" : "getDeviceList",
			"subscribeAlarmBtn" : "subscribeAlarm",
			"creatediskpoolBtn" : "Create DiskPool",
			"createstoragepoolBtn" : "Create StoragePool",
			"createLUNBtn" : "Create LUN",
			"createLUNGroupBtn" : "Create LUNGroup",
			"createHostBtn" : "Create Host",
			"createHostGroupBtn" : "Create HostGroup",
			"createPortGroupBtn" : "Create PortGroup",
			"createMappingViewBtn" : "Users create a virtual machine"
		},

		titles : {
			"descriptionIVS" : "The OpenAPI developed based on the local JAR. The OpenAPI provides the authentication, basic devices, hardware, system management, and value-added service functions of Huawei storage products for third-party systems, masking off complicated underlying protocols and technologies. In addition, this document provides code samples for your reference, helping you quickly integrate and use functions of storage arrays.",
			"copyright" : "Copyright © Huawei Technologies Co., Ltd. 1998-2014. All rights reserved.",
			"description" : "Description",
			"exection" : "Execution",
			"sourceCode" : "Source Code",
			"resultCode" : "resultCode:",
			"inputParameterDesc" : "input parameters description:",
			"outputParameterDesc" : "output parameters description:",
			"inputParameterTd" : "parameter",
			"inputTypeTd" : "type",
			"inputRestrictionTd" : "restriction",
			"inputDescriptionTd" : "description",
			"outputParameterTd" : "parameter",
			"outputTypeTd" : "type",
			"outputRestrictionTd" : "restriction",
			"outputDescriptionTd" : "description",
			"resultCodeTd" : "for successful return zero, and failed return other codes",
			"operationSuccess" : "operation success",
			"operationFailed" : "operation failed",
			"reserveTd32" : "Reserved field<br>The maximum length is 32 bytes",
			"reserveTd64" : "Reserved field<br>The maximum length is 64 bytes",
			"fromIndex" : "Starting index<br>A positive integer, starting at 1",
			"toIndex" : "End index<br>A positive integer, must be greater than the starting index, the maximum length of 5000 records paging, that 0 <= (end index - the starting index) <= 5000",
			
			"createDiskPool_sourceCode" : "Create Disk Domain",
			"createDiskPool_div" : "Create Disk Domain",
			"createStoragePool_sourceCode" : "Create Storage Pool",
			"createStoragePool_div" : "Create Storage Pool",
			"createLun_sourceCode" : "Create LUN",
			"createLun_div" : "Create LUN",
			"createHost_sourceCode":"Create Host",
			"createHost_div":"Create Host",
			"createLunGroup_sourceCode":"Create LUN Group",
			"createLunGroup_div":"Create LUN Group",
			"createHostGroup_sourceCode":"Create Host Group",
			"createHostGroup_div":"Create Host Group",
			"createPortGroup_sourceCode":"Create Port Group",
			"createPortGroup_div":"Create Port Group",
			"createMappingView_sourceCode":"Create Mapping View",
			"createMappingView_div":"Create Mapping View",
			"time_sourceCode":"Occurrence Time",
			"description_sourceCode":"Description",
			
			"ivsTree_1_span" : "Typical scenarios",
			"ivsTree_2_span" : "Third-party management",
			"ivsTree_3_span" : "System Information",
			"ivsTree_4_span" : "Third party collect alarms",

			"ivsTree_2_span_tag" : "Create a map ",
			"ivsTree_3_span_tag" : "Get system information data ",
			"ivsTree_4_span_tag" : "Get the current alarm information",
			
			"getAlarmEventInfoInterface" : "Function Name：getAlarmEventInfo<br/>",
			"getAlarmEventInfoDesc" : "This is used to query alarm event info",
			"userNameLabel" : "User Name:",
			"alarmEventIdInputTd" : "alarmEventId",
			"passwordLabel" : "Password:",
			"hostLocationLabel" : "Device Location:",
			"ipLabel" : "device IP：",
			"initiatorLabel" : "Initiator:",
			"portLabel" : "Port：",
			"nameLabel" : "Name:",
			"nameErrTip" : "Name can not be empty",
			"operationSystemLabel" : "Operating system:",
			"storagepoolIdLabel" : "Storage Pool:",
			"storagepoolIdErrTip" : "Storage pool ID can not be empty",
			"userConsumedCapacityThresholdLabel" : "Used capacity threshold values:",
			"userConsumedCapacityThresholdErrTip" : "Used capacity threshold values can not be empty",
			"userConsumedCapacityThresholdErrTipIsNumber" : "Used capacity threshold only be integer",
			"capacityErrTip" : "Capacity can not be empty",
			"capacityIsNumber" : "Capacity only be integer",
			"diskLabel" : "Hard disk type:",
			"diskNumberLabel" : "The selected number of hard disk：",
			"userNameNull" : "Username can not be empty",
			"passwordNull" : "The password can not be empty",
			"ipNull" : "Device IP can not be empty",
			"portNull" : "Device port number can not be empty",
			"portIsNumber" : "Device port number must be an integer",
			"diskIsNumber" : "Hard disk must be an integer number",
			"passwordNull" : "The password can not be empty",
			"diskNumberNull" : "The number can not be empty",
			"idLabel" : "ID:",
			"descriptionLabel" : "Description:",
			"diskpoolIdLabel" : "DiskPool ID:",
			"diskpoolIdErrTip" : "DiskPool can not be empty",
			"lunCapacityLabel" : "LUN capacity:",
			"managerStorageLable" : "Third-party management",
			"collectAlarmLable" : "Third party collect alarms",
			"lunCapacityIsNullErrTip" : "LUN capacity can not be empty",
			"lunCapacityIsNumberErrTip" : "LUN capacity only be integer",
			"lunIdLabel" : "Add LUN:",
			"hostIdLabel" : "Add Host:",
			"portIdLabel" : "Add port:",
			"hostgroupMapLabel" : "Host Group：",
			"lungroupMapLabel" : "LUN group",
			"portgroupMapLabel" : "Port Group",
			"deviceIdLabel" : "Device serial number:",
			"deviceNameLabel" : "Device Name:",
			"deviceLocationLabel" : "Device location information:",
			"deviceHealthLabel" : "Device health status:",
			"deviceRunningLabel" : "Device operating status:",
			"deviceDescriptionLabel" : "Device description:",
			"deviceModeLabel" : "Device Model:",
			"deviceVersionLabel" : "Device version information:",
			"devicewwnLabel" : "WWN（World Wide Number）:",
			"deviceStatusLabel" : "System Status:",
			"deviceTimeLabel" : "Current time:",
			"perfDataLabel" : "Performance value:",
			"lastLabel" : "Previous",
			"nextLabel" : "Next",
			"loginUserNameLabel" : "Login User: "

		}
	};
}