function LanguageControllerZH() {
	this.language = {
		buttons : {
			"loginBtn" : "登     录",
			"getDeviceListBtn" : "获取子设备列表",
			"subscribeAlarmBtn" : "订阅告警",
			"creatediskpoolBtn" : "创建硬盘域",
			"createstoragepoolBtn" : "创建存储池",
			"createLUNBtn" : "创建LUN",
			"createLUNGroupBtn" : "创建LUN组",
			"createHostBtn" : "创建主机",
			"createHostGroupBtn" : "创建主机组",
			"createPortGroupBtn" : "创建端口组",
			"createMappingViewBtn" : "用户创建虚拟机"
		},

		titles : {
			"descriptionIVS" : "eSDK IVS以本地JAR包形式开放OpenAPI接口，向第三方系统提供华为存储阵列产品中的鉴权、基础设备、硬件、系统管理、增值业务功能，屏蔽了复杂的底层协议和技术细节，使用户可以更加方便快速的集成和使用存储阵列中的功能。",
			"copyright" : "版权所有 © 华为技术有限公司 1998-2014。 保留一切权利。粤A2-20044005号",
			"description" : "说明",
			"exection" : "执行",
			"sourceCode" : "代码示例:",
			"resultCode" : "结果码:",
			"inputParameterDesc" : "输入参数描述:",
			"outputParameterDesc" : "返回参数描述:",
			"inputParameterTd" : "参数",
			"inputTypeTd" : "类型",
			"inputRestrictionTd" : "约束",
			"inputDescriptionTd" : "描述",
			"outputParameterTd" : "参数",
			"outputTypeTd" : "类型",
			"outputRestrictionTd" : "约束",
			"outputDescriptionTd" : "描述",
			"resultCodeTd" : "成功返回0，失败返回错误码",
			"operationSuccess" : "操作成功",
			"operationFailed" : "操作失败",
			"reserveTd32" : "保留字段<br>长度限制32字节",
			"reserveTd64" : "保留字段<br>长度限制64字节",
			"fromIndex" : "开始索引<br>正整数，从1开始",
			"toIndex" : "结束索引<br>正整数，必须大于开始索引，最大分页长度为5000条记录，即0<=（结束索引-开始索引）<= 5000",

			"createDiskPool_sourceCode" : "创建硬盘域",
			"createDiskPool_div" : "创建硬盘域",
			"createStoragePool_sourceCode" : "创建存储池",
			"createStoragePool_div" : "创建存储池",
			"createLun_sourceCode" : "创建LUN",
			"createLun_div" : "创建LUN",
			"createHost_sourceCode" : "创建主机",
			"createHost_div" : "创建主机",
			"createLunGroup_sourceCode" : "创建LUN组",
			"createLunGroup_div" : "创建LUN组",
			"createHostGroup_sourceCode" : "创建主机组",
			"createHostGroup_div" : "创建主机组",
			"createPortGroup_sourceCode" : "创建端口组",
			"createPortGroup_div" : "创建端口组",
			"createMappingView_sourceCode" : "创建映射视图",
			"createMappingView_div" : "创建映射视图",
			"time_sourceCode" : "发生时间",
			"description_sourceCode" : "描述",

			"ivsTree_1_span" : "典型场景",
			"ivsTree_2_span" : "被第三方管理场景",
			"ivsTree_3_span" : "系统信息",
			"ivsTree_4_span" : "第三方搜集告警场景",

			"ivsTree_2_span_tag" : "创建映射 ",
			"ivsTree_3_span_tag" : "获取系统信息数据 ",
			"ivsTree_4_span_tag" : "获取当前告警信息",

			"getAlarmEventInfoInterface" : "接口名称：getAlarmEventInfo（查询告警事件信息）<br/>",
			"getAlarmEventInfoDesc" : "此接口用于查询告警事件信息",

			"userNameLabel" : "用户名:",
			"alarmEventIdInputTd" : "告警事件ID",
			"passwordLabel" : "密   码:",
			"hostLocationLabel" : "设备位置:",
			"ipLabel" : "IP地址:",
			"initiatorLabel" : "启动器:",
			"portLabel" : "端口号:",
			"nameLabel" : "名称:",
			"nameErrTip" : "名称不能为空",
			"operationSystemLabel" : "操作系统:",
			"storagepoolIdLabel" : "存储池:",
			"storagepoolIdErrTip" : "存储池ID不能为空",
			"userConsumedCapacityThresholdLabel" : "已用容量阈值:",
			"userConsumedCapacityThresholdErrTip" : "已用容量阀值不能为空",
			"userConsumedCapacityThresholdErrTipIsNumber" : "已用容量阀值只能为整数",
			"capacityErrTip" : "容量不能为空",
			"capacityIsNumber" : "容量只能为整数",
			"diskLabel" : "硬盘类型:",
			"diskNumberLabel" : "所选硬盘数：",
			"userNameNull" : "用户名不能为空",
			"passwordNull" : "密码不能为空",
			"ipNull" : "设备IP不能为空",
			"portNull" : "设备端口号不能为空",
			"portIsNumber" : "设备端口号必须为整数",
			"diskIsNumber" : "硬盘数必须为整数",
			"passwordNull" : "密码不能为空",
			"diskNumberNull" : "数量不能为空",
			"idLabel" : "ID:",
			"descriptionLabel" : "描述:",
			"diskpoolIdLabel" : "硬盘域ID:",
			"diskpoolIdErrTip" : "硬盘域不能为空",
			"lunCapacityLabel" : "LUN容量:",
			"managerStorageLable" : "第三方管理存储设备",
			"collectAlarmLable" : "第三方搜集告警",
			"lunCapacityIsNullErrTip" : "LUN容量不能为空",
			"lunCapacityIsNumberErrTip" : "LUN容量只能为整数",
			"lunIdLabel" : "添加LUN:",
			"hostIdLabel" : "添加主机:",
			"portIdLabel" : "添加端口:",
			"hostgroupMapLabel" : "主机组：",
			"lungroupMapLabel" : "LUN组",
			"portgroupMapLabel" : "端口组",
			"deviceIdLabel" : "设备序列号:",
			"deviceNameLabel" : "设备名称:",
			"deviceLocationLabel" : "设备位置信息:",
			"deviceHealthLabel" : "设备健康状态:",
			"deviceRunningLabel" : "设备运行状态:",
			"deviceDescriptionLabel" : "设备描述信息:",
			"deviceModeLabel" : "设备型号:",
			"deviceVersionLabel" : "设备版本信息:",
			"devicewwnLabel" : "WWN（World Wide Number）:",
			"deviceStatusLabel" : "系统状态:",
			"deviceTimeLabel" : "当前时间:",
			"perfDataLabel" : "性能值:",
			"lastLabel" : "上一页",
			"nextLabel" : "下一页",
			"loginUserNameLabel" : "登录用户: "

		}
	};
}