/**
 * Generated by Agitar build: AgitarOne Version 6.0.0.000018 (Build date: Sep 06, 2013) [6.0.0.000018]
 * JDK Version: 1.6.0_14
 *
 * Generated on 2014-3-11 13:33:27
 * Time to generate: 00:08.625 seconds
 *
 *
 * agitar.src.md5=com.huawei.ism.openapi.common.keydeifines.IsmConstant:aad8178fa07e42eda310268e4e979fd3
 *
 */

package com.huawei.ism.openapi.common.keydeifines;

import com.agitar.lib.junit.AgitarTestCase;

public class IsmConstantAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return IsmConstant.class;
    }
    
    public void testConstructor() throws Throwable {
        new IsmConstant();
        assertTrue("Test call resulted in expected outcome", true);
    }
}

